import Profile1 from '../../../assets/icons/profile1.png';
import Profile2 from '../../../assets/icons/profile2.png';
import Profile3 from '../../../assets/icons/profile3.png';

export const TableDATA = [
    {
        id:1,
        img:Profile1,
        fullname:'Lindsey Stroud',
        email:'lindsey.stroud@gmail.com',
        comp_name:'Clockify',
        role:'Manager',
        forecast:'50%',
        active:'5 minutes ago',
    },
    {
        id:2,
        img:Profile2,
        fullname:'Nicci Troiani',
        email:'nicci.troiani@gmail.com',
        comp_name:'Upwork',
        role:'Manager',
        forecast:'50%',
        active:'5 minutes ago',
    },
    {
        id:3,
        img:Profile3,
        fullname:'George Fields',
        email:'george.fields@gmail.com',
        comp_name:'Developer',
        role:'CEO',
        forecast:'80%',
        active:'10 minutes ago',
    },
    {
        id:1,
        img:Profile1,
        fullname:'Lindsey Stroud',
        email:'lindsey.stroud@gmail.com',
        comp_name:'Clockify',
        role:'Manager',
        forecast:'50%',
        active:'5 minutes ago',
    },
    {
        id:2,
        img:Profile2,
        fullname:'Nicci Troiani',
        email:'nicci.troiani@gmail.com',
        comp_name:'Upwork',
        role:'Manager',
        forecast:'50%',
        active:'5 minutes ago',
    },
    {
        id:3,
        img:Profile3,
        fullname:'George Fields',
        email:'george.fields@gmail.com',
        comp_name:'Developer',
        role:'CEO',
        forecast:'80%',
        active:'10 minutes ago',
    },
    {
        id:1,
        img:Profile1,
        fullname:'Lindsey Stroud',
        email:'lindsey.stroud@gmail.com',
        comp_name:'Clockify',
        role:'Manager',
        forecast:'50%',
        active:'5 minutes ago',
    },
    {
        id:2,
        img:Profile2,
        fullname:'Nicci Troiani',
        email:'nicci.troiani@gmail.com',
        comp_name:'Upwork',
        role:'Manager',
        forecast:'50%',
        active:'5 minutes ago',
    }
]