export const TestDATA = [
    {
        id:1,
        question:'Html da forma toldirishda ishlatiladigon atributni ko’rsating',
        true_answer:'<form>',
        choice:[
            {
                id:1,
                name:'<body>'
            },
            {
                id:2,
                name:'<form>'
            },
            {
                id:3,
                name:'<div>'
            },
            {
                id:4,
                name:'<li>'
            }
        ],
        isanswered:false,
        chosen_answer:null
    },
    {
        id:2,
        question:'Html da rasm ishlatiladigon tag ko’rsating',
        true_answer:'<img>',
        choice:[
            {
                id:1,
                name:'<body>'
            },
            {
                id:2,
                name:'<img>'
            },
            {
                id:3,
                name:'<div>'
            },
            {
                id:4,
                name:'<li>'
            }
        ],
        isanswered:false,
        chosen_answer:null
    },
    {
        id:3,
        question:'Html da div toldirishda ishlatiladigon atributni ko’rsating',
        true_answer:'<div>',
        choice:[
            {
                id:1,
                name:'<body>'
            },
            {
                id:2,
                name:'<form>'
            },
            {
                id:3,
                name:'<div>'
            },
            {
                id:4,
                name:'<li>'
            }
        ],
        isanswered:false,
        chosen_answer:null
    },
]